# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cate_id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u5206\u7c7bID')),
                ('name', models.CharField(max_length=64, verbose_name='\u5206\u7c7b\u540d\u79f0')),
                ('description', models.CharField(max_length=512, verbose_name='\u5206\u7c7b\u63cf\u8ff0')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u6587\u7ae0\u771f\u5b9eID')),
                ('post_uuid', models.UUIDField(default=uuid.uuid1, verbose_name='\u6587\u7ae0\u4f2a\u88c5ID')),
                ('title', models.CharField(max_length=256, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('abstract', models.CharField(max_length=256, verbose_name='\u6587\u7ae0\u6458\u8981')),
                ('content', models.TextField(default='', null=True, verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('status', models.CharField(choices=[('0', '\u53d1\u5e03'), ('1', '\u8349\u7a3f')], default='0', max_length=1, verbose_name='\u6587\u7ae0\u72b6\u6001')),
                ('is_reprint', models.BooleanField(default=False, verbose_name='\u8f6c\u8f7d')),
                ('reprint_src', models.CharField(blank=True, max_length=512, null=True, verbose_name='\u8f6c\u8f7d\u6e90')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='blog.Category', verbose_name='\u6587\u7ae0\u5206\u7c7b')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='blog.Tag', verbose_name='\u6587\u7ae0\u6807\u7b7e'),
        ),
    ]
