# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='\u7f6e\u9876'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_category_posts', to='blog.Category', verbose_name='\u6587\u7ae0\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='in_tag_posts', to='blog.Tag', verbose_name='\u6587\u7ae0\u6807\u7b7e'),
        ),
    ]
