# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181126_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='dict',
            name='comment',
            field=models.CharField(default='', max_length=256, verbose_name='\u5907\u6ce8'),
        ),
    ]
