# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-02 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181030_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=256, unique=True, verbose_name='\u6587\u7ae0\u6807\u9898'),
        ),
    ]
