# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-02 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181102_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.TextField(max_length=128)),
                ('content', models.TextField(max_length=2048)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='\u6d4f\u89c8\u91cf'),
        ),
        migrations.AddField(
            model_name='comment',
            name='in_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post'),
        ),
    ]
