# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-01 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_dict_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMeta',
            fields=[
                ('post_meta_id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u6587\u7ae0metaID')),
                ('title', models.TextField(default='', max_length=128, verbose_name='meta\u6807\u9898')),
                ('content', models.TextField(default='', max_length=2048, verbose_name='meta\u5185\u5bb9')),
                ('in_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='blog.Post', verbose_name='\u6240\u5c5e\u6587\u7ae0')),
            ],
        ),
    ]
