# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-02 09:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181102_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 11, 2, 17, 24, 54, 585000), verbose_name='\u8bc4\u8bba\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.TextField(default='\u65e0\u9898', max_length=256, verbose_name='\u8bc4\u8bba\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.TextField(max_length=128, verbose_name='\u8bc4\u8bba\u8005'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=2048, verbose_name='\u8bc4\u8bba\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='\u90ae\u7bb1\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='in_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post', verbose_name='\u6240\u5c5e\u6587\u7ae0'),
        ),
    ]
