# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-10 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postmeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='\u6587\u7ae0\u4f2a\u88c5ID'),
        ),
    ]
