# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-14 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190210_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='in_tag_posts', to='blog.Tag', verbose_name='\u6587\u7ae0\u6807\u7b7e'),
        ),
    ]
