# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-04 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181104_0801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AddField(
            model_name='comment',
            name='floor',
            field=models.IntegerField(default=1, verbose_name='\u697c\u5c42'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.CharField(default='', max_length=32, verbose_name='\u56de\u590d\u697c\u5c42'),
        ),
    ]
