# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181104_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='\u6570\u636e\u5b57\u5178\u952e')),
                ('value', models.CharField(max_length=1024, verbose_name='\u6570\u636e\u5b57\u5178\u503c')),
                ('category', models.CharField(default='default', max_length=16, verbose_name='\u9879\u5206\u7c7b')),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
