# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181105_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='greats',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\u91cf'),
        ),
    ]
