# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20181108_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='\u5206\u7c7b\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='message',
            name='contact',
            field=models.CharField(max_length=128, null=True, verbose_name='\u8054\u7cfb\u65b9\u5f0f'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(default='\u65e0\u9898', max_length=128, verbose_name='\u6807\u9898'),
        ),
    ]
