# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-14 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paper_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='\u8bba\u6587UUID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='\u8bba\u6587\u6807\u9898')),
                ('publish_time', models.DateField(verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('publish_origin', models.CharField(default='unknown', max_length=128, verbose_name='\u53d1\u8868\u520a\u7269/\u4f1a\u8bae')),
                ('self_score', models.IntegerField(default=-1, verbose_name='\u6253\u5206')),
                ('link', models.URLField(null=True, verbose_name='\u8bba\u6587\u94fe\u63a5')),
                ('author', models.ManyToManyField(related_name='papers', to='paperdb.Author', verbose_name='\u4f5c\u8005')),
            ],
        ),
        migrations.CreateModel(
            name='PaperComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('content', models.TextField(default='', verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchTag',
            fields=[
                ('research_tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(default='', max_length=512, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='comment',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper', to='paperdb.PaperComment', verbose_name='\u8bc4\u8bba'),
        ),
        migrations.AddField(
            model_name='paper',
            name='reference',
            field=models.ManyToManyField(blank=True, related_name='_paper_reference_+', to='paperdb.Paper', verbose_name='\u5f15\u7528'),
        ),
        migrations.AddField(
            model_name='paper',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='papers', to='paperdb.ResearchTag', verbose_name='\u7814\u7a76\u65b9\u5411\u6807\u7b7e'),
        ),
    ]
