# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-15 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paperdb', '0002_auto_20190614_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('reference_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='paper',
            name='reference',
        ),
        migrations.AddField(
            model_name='reference',
            name='reference_src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='paperdb.Paper', verbose_name='\u5f15\u7528\u6e90'),
        ),
        migrations.AddField(
            model_name='reference',
            name='reference_trg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='be_referred', to='paperdb.Paper', verbose_name='\u88ab\u5f15\u7528\u6e90'),
        ),
        migrations.AlterUniqueTogether(
            name='reference',
            unique_together=set([('reference_src', 'reference_trg')]),
        ),
    ]
