# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-21 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paperdb', '0003_auto_20190615_1517'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together=set([('name',)]),
        ),
    ]
