# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-02-08 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WyzCoup',
            fields=[
                ('coup_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('coup_status', models.CharField(choices=[('0', '\u672a\u4f7f\u7528'), ('1', '\u5df2\u4f7f\u7528'), ('2', '\u5df2\u8fc7\u671f')], default='0', max_length=1, verbose_name='\u597d\u4eba\u5361\u72b6\u6001')),
                ('consume_time', models.DateTimeField(default=None, null=True, verbose_name='\u4f7f\u7528\u65f6\u95f4')),
                ('expire_time', models.DateTimeField(default=None, null=True, verbose_name='\u8fc7\u671f\u65f6\u95f4')),
                ('coup_title', models.CharField(max_length=128, verbose_name='\u597d\u4eba\u5361\u6807\u9898')),
                ('coup_content', models.CharField(default='', max_length=1024, verbose_name='\u597d\u4eba\u5361\u5185\u5bb9')),
                ('coup_note', models.CharField(default='', max_length=2048, verbose_name='\u597d\u4eba\u5361\u4f7f\u7528\u5907\u6ce8')),
            ],
        ),
    ]
