# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import ftkuser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('ac_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_ip', ftkuser.fields.IPyIPSegmentField(max_length=32)),
                ('control_type', models.CharField(choices=[('0', '\u767d\u540d\u5355'), ('1', '\u9ed1\u540d\u5355')], max_length=2)),
                ('domain', models.CharField(default='root', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Slogan',
            fields=[
                ('slogan_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=1024)),
                ('author', models.TextField(max_length=128)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='accesscontrol',
            unique_together=set([('source_ip', 'control_type', 'domain')]),
        ),
    ]
