# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-02 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slogan',
            fields=[
                ('slogan_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=1024)),
                ('author', models.TextField(max_length=128)),
            ],
        ),
    ]
