# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftkuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('source_ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('control_type', models.CharField(choices=[('0', '\u767d\u540d\u5355'), ('1', '\u9ed1\u540d\u5355')], max_length=2)),
                ('domain', models.CharField(default='root', max_length=32)),
            ],
        ),
    ]
