# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftkuser', '0002_accesscontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontrol',
            name='ac_id',
            field=models.AutoField(default=-1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accesscontrol',
            name='source_ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterUniqueTogether(
            name='accesscontrol',
            unique_together=set([('source_ip', 'control_type')]),
        ),
    ]
