# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 08:26
from __future__ import unicode_literals

from django.db import migrations
import ftkuser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ftkuser', '0004_auto_20181109_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrol',
            name='source_ip',
            field=ftkuser.fields.IPyIPSegmentField(max_length=256),
        ),
    ]
